### ISSUE TITLE
Media manager and item image issues

### ISSUE THREAD

**Issue by cantgetmyusername** [getk2/k2-v3-dev-build#237]
Blank modal

Cannot add images of any kind in any way. (Another build in 2.6.9 doe not have this issue.)

J 3.4.3 in blank Helix III. No security apps. This is not a production site

The console reports only:
/site/media/k2app/app/views/filters.js?1440677194099:82 Uncaught TypeError: this.$(...).select2 is not a function
/site-/media/k2app/app/widget.js?1440677194099:21 Uncaught TypeError: labels.tipr is not a function
/site/media/k2app/app/views/filters.js?1440677194099:82 Uncaught TypeError: this.$(...).select2 is not a function
/site/media/k2app/app/widget.js?1440677194099:21 Uncaught TypeError: labels.tipr is not a function
/site/media/k2app/app/views/media/manager.js?1440677194099:20 Uncaught TypeError: this.$el.elfinder is not a function

**Comment by paulvanharen** [comment]
I could not reproduce this issue.
